POST http://localhost:8080/v1/chat/completions
Authorization: Bearer hf_xxxx
Content-Type: application/json

{
    "model": "gpt-4o",
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "You are a helpful assistant. Please answer the user's questions based on the image provided if image is available.If the image is available, please answer in a concise and informative manner in a single sentence as one phrase.If the image is not available, please answer the question based on your knowledge.If tools are available, please use them to answer the question."
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "What is in this image?"
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://picsum.photos/id/237/200/300",
                        "detail": "low"
                    }
                }
            ]
        }
    ],
    "max_tokens": 300
}
